name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Node & NPM versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          set -ex
          npm install

      - name: Build
        run: |
          set -ex
          npm run build

      - name: List build folder
        run: |
          set -ex
          ls -la
          ls -la build || echo "NO BUILD FOLDER"
          ls -la dist || echo "NO DIST FOLDER"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy to S3
        run: |
          set -ex
          aws s3 sync dist/ s3://ctrackr-website-prod --delete

      - name: Invalidate CloudFront
        run: |
          set -ex
          aws cloudfront create-invalidation \
            --distribution-id E3OJLQS0UXAUC5 \
            --paths "/*"